GET http://localhost:3000/camisetas HTTP/1.1

###
GET http://localhost:3000/camisetas/1 HTTP/1.1


###
POST http://localhost:3000/camisetas HTTP/1.1
Content-Type: application/json

{
  "name": "Camiseta urbana",
  "brand": "adidas",
  "size": "m",
  "color": "azul",
  "price": 200.99
}


###
PUT http://localhost:3000/camisetas/3 HTTP/1.1
Content-Type: application/json

{
  "price": 29.99
}

###
DELETE http://localhost:3000/camisetas/2 HTTP/1.1
